'use client';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Mail, Menu, X, ExternalLink } from 'lucide-react';
import { profile, education, internships, skills, certifications, events, projects } from '@/data/content';

const nav = [['about','ABOUT'],['journey','JOURNEY'],['work','WORK'],['skills','SKILLS'],['certifications','CERTS'],['events','EVENTS'],['contact','CONTACT']];

export default function Home(){
 const [menu,setMenu]=useState(false); const [active,setActive]=useState(0);
 const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};
 return <main>
  <nav className="nav"><button className="brand" onClick={()=>go('home')}>SK<span>•</span></button><div className="desktopNav">{nav.map(([id,label])=><button key={id} onClick={()=>go(id)}>{label}</button>)}</div><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>
  {menu&&<div className="mobileNav">{nav.map(([id,label])=><button key={id} onClick={()=>go(id)}>{label}</button>)}</div>}
  <section id="home" className="hero"><div className="gridBg"/><div className="heroTop"><span>COIMBATORE · INDIA</span><span>AVAILABLE TO BUILD</span></div><div className="heroContent"><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="eyebrow">AI / CLOUD / SOFTWARE ENGINEERING</motion.p><motion.h1 initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{delay:.1}}>SANJEEV<br/><em>KESAVAN</em></motion.h1><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.3}} className="heroBottom"><p>{profile.headline}</p><button className="circleCta" onClick={()=>go('about')}><ArrowDownRight/></button></motion.div></div><div className="heroTech"><span>REACT</span><span>NEXT.JS</span><span>GEMINI</span><span>AWS</span><span>DOCKER</span><span>TERRAFORM</span></div></section>
  <section id="about" className="section about"><div className="sectionLabel">01 / ABOUT</div><div className="split"><h2>THE PERSON<br/><span>BEHIND THE CODE.</span></h2><div><p className="lead">{profile.bio}</p><div className="process"><span>PROBLEM</span><i>→</i><span>IDEA</span><i>→</i><span>DESIGN</span><i>→</i><span>BUILD</span><i>→</i><span>DEPLOY</span></div></div></div></section>
  <section id="journey" className="section journey"><div className="sectionLabel">02 / JOURNEY</div><div className="split"><h2>EDUCATION<br/><span>& EXPERIENCE.</span></h2><div className="timeline"><div className="timelineTitle">EDUCATION</div>{education.map((e)=><article className="timelineItem" key={e.title}><span>{e.year}</span><div><small>{e.tag}</small><h3>{e.title}</h3><p>{e.subtitle}</p></div></article>)}<div className="timelineTitle space">INTERNSHIPS</div>{internships.map((e)=><article className="timelineItem" key={e.company+e.year}><span>{e.year}</span><div><h3>{e.company}</h3><p>{e.role}</p></div></article>)}</div></div></section>
  <section id="work" className="section work"><div className="sectionLabel">03 / SELECTED WORK</div><div className="workHeader"><h2>PRODUCTS<br/><span>I'VE BUILT.</span></h2><p>Five projects. One mindset: solve something real, then engineer the experience around it.</p></div><div className="projectList">{projects.map((p,i)=><motion.article whileHover={{x:8}} className="project" key={p.title} onMouseEnter={()=>setActive(i)}><div className="projectNo">{p.n}</div><div className="projectMain"><p>{p.kicker}</p><h3>{p.title}</h3><span>{p.desc}</span></div><div className="projectArrow"><ArrowUpRight/></div><div className="projectGlow"/></motion.article>)}</div><div className="projectDetail"><div><span>FEATURED / {projects[active].n}</span><h3>{projects[active].title}</h3></div><p>{projects[active].detail}</p></div></section>
  <section id="skills" className="section skills"><div className="sectionLabel">04 / ENGINEERING STACK</div><h2>TOOLS I USE TO<br/><span>TURN IDEAS INTO SYSTEMS.</span></h2><div className="skillGrid">{Object.entries(skills).map(([cat,items])=><div className="skillCard" key={cat}><p>{cat}</p><div>{items.map(x=><span key={x}>{x}</span>)}</div></div>)}</div></section>
  <section id="certifications" className="section certs"><div className="sectionLabel">05 / CERTIFICATIONS</div><div className="split"><h2>LEARNING<br/><span>IN PUBLIC.</span></h2><div className="certGrid">{certifications.map(([org,name],i)=><div className="cert" key={name}><span>0{i+1}</span><small>{org}</small><h3>{name}</h3><p>COMPLETED / TRACKING</p></div>)}</div></div></section>
  <section id="events" className="section events"><div className="sectionLabel">06 / EVENTS & ACHIEVEMENTS</div><div className="stats">{events.map(([num,title,desc])=><div className="stat" key={title}><strong>{num}</strong><h3>{title}</h3><p>{desc}</p></div>)}</div></section>
  <section className="section beyond"><div className="sectionLabel">07 / BEYOND CODE</div><div className="beyondGrid"><h2>THE HUMAN<br/><span>SIDE.</span></h2><div className="chips"><span>♟ State-Level Chess Player</span><span>IMUN Club</span><span>YRC Blood Donation</span><span>Tamil</span><span>English</span><span>Hindi</span><span>Design Thinking</span><span>Problem Solving</span></div></div></section>
  <section id="contact" className="contact"><div className="contactNoise"/><p>08 / CONTACT</p><h2>LET'S BUILD<br/><em>SOMETHING MEANINGFUL.</em></h2><div className="contactLinks"><a href={profile.github} target="_blank" rel="noreferrer">GITHUB <ExternalLink/></a><a href={profile.linkedin} target="_blank" rel="noreferrer">LINKEDIN <ExternalLink/></a><a href="mailto:sanjeev@example.com">EMAIL <Mail/></a></div><footer><span>© 2026 SANJEEV KESAVAN</span><span>AI × CLOUD × FULL STACK × DEVOPS</span></footer></section>
 </main>
}